version: '3.7'

services:
  # BackEnd API
  smartbrain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smartBrain-api
    ports: 
      - "3000:3000"
    volumes:
      - ./:/usr/src/smartBrain-api


  # Postgres
  
